### PR TITLE
Combined Review Page & Business Page Implementations

### PR DESCRIPTION
**Pull request by matthewdbroom13**
Implements both the review page and business page functionality while also fixing console errors for those pages

### CODE REVIEW

**Review by aedanmc — DISMISSED** [review]
It looks like this PR reintroduces `betaApp.js` to main after it was removed; please confirm that the refactor of the back end is included in this PR!

**Comment by matthewdbroom13** [comment]
Not sure why betaApp was in there, completely missed it too! It is gone now and everything appears to work just as well as when betaApp was still there. Thankfully the back-end refactor is accounted for on the branch, I think there must have been a merge that kept betaApp while also adding app.js

**Review by mik3ycodez — APPROVED** [review]
Other than some commented out code and a few console statements. Good for final release. 
LGTM

**Review by C-Christensen — APPROVED** [review]
LGTM

**Review by aedanmc — APPROVED** [review]
Looks good to me, now that the extra files are removed :)

**Pull request merged**
