### PR TITLE
Search endpoint

### PR DESCRIPTION
**Pull request by mik3ycodez**
- [x] Added Google Places API to Search and Business endpoints
- [x] Added Reviews endpoint 
- [x] Alphabetized endpoints and their tests

### CODE REVIEW

**Comment by mik3ycodez** [comment]
Due to issues with the front end routing, we are not merging this pull request. Will provide updates.

**Comment by mik3ycodez** [comment]
Build failing due to front end tests

**Review by C-Christensen — APPROVED** [review]
LGTM

**Comment by mik3ycodez** [comment]
Regarding conflict in SearchPage.js - I think we're keeping this PR update. @C-Christensen, can you confirm?

**Comment by mik3ycodez** [comment]
Also, are we still holding on merging this PR? That was only until the routing issue could be resolved.

**Comment by C-Christensen** [comment]
> SearchPag

Let me take a look on what the merge conflict is because front-end has done some modifications to this page to get the router working and I want to make sure we are not overriding their changes. I'll resolve the conflict by EOD.

**Review by C-Christensen — APPROVED** [review]
Merge conflict resolved. We can merge these changes to main :)

**Pull request merged**
