### PR TITLE
Changes to the developer guide

### PR DESCRIPTION
**Pull request by C-Christensen**
- Added versioning process information 
- Finalized back-end test documentation
- Changed naming convention for back-end test files
- Minor update to database test file to reflect the documentation instructions

### CODE REVIEW

**Review by mik3ycodez — CHANGES_REQUESTED** [review]
BETESTIGDOC.md will need updated testing documentation. My implementation of server testing will change some instructions. Will communicate in person so that is reflected in this file.

**Review by mik3ycodez — APPROVED** [review]
OMGucci!! @C-Christensen this is amazing!!!! Great job!

**Review by aedanmc — APPROVED** [review]
Looks good! Only minor change I might suggest is changing "Sanity Checks" to "Safety Checks" if we want to avoid any ableist language surrounding mental illness.

**Review by mzuniga-1833381 — APPROVED** [review]
LGTM!

**Review by matthewdbroom13 — APPROVED** [review]

**Pull request merged**
