### PR TITLE
Business Page Implementation

### PR DESCRIPTION
**Pull request by matthewdbroom13**
Completes the business/location page, including a link to post a review.

### CODE REVIEW

**Review by mzuniga-1833381 — COMMENTED** [review]
Looks like there's a failing PR error - we should resolve this before merging

**Comment by mzuniga-1833381** [comment]
You're missing an import statement for the `<Outlet>` component. I'll go in and change that now and hopefully it'll pass.

**Review by mzuniga-1833381 — APPROVED** [review]
LGTM

**Review by mzuniga-1833381 — CHANGES_REQUESTED** [review]
This passes the checks for GCP, but if you open the console on the localhost, you'll actually see a multitude of errors. I think these need to be cleaned up before this can be merged to main
Screen Shot 2022-05-30 at 12 41 36 PM

**Comment by matthewdbroom13** [comment]
For the purposes of the demo, I think this PR is okay to merge as the functionality works. The console errors are not ideal but I feel they are less of a priority due to them not impacting the usability of the app from my usability testing.

**Review by C-Christensen — CHANGES_REQUESTED** [review]
Some of the warnings can be removed if you update the propTypes in LocationDetails. Currently the props are set as required, but if you remove that and add a defaultProp value that should eliminate some of the warnings. 

`Example below: `
LocationDetails.propTypes = {
  image: PropTypes.string,
  name: PropTypes.string,
  address: PropTypes.string,
  phone: PropTypes.string,
  link: PropTypes.string,
  equalityScore: PropTypes.string,
  numReviews: PropTypes.string,
  googleRating: PropTypes.number,
  numRatings: PropTypes.number,
  country: PropTypes.string,
  countrySafety: PropTypes.string,
};

LocationDetails.defaultProps = {
  image: '',
  name: '',
  address: '',
  phone: '',
  link: '',
  equalityScore: '',
  numReviews: '',
  googleRating: '',
  numRatings: '',
  country: '',
  countrySafety: '',
};

**Comment by C-Christensen** [comment]
Other warning has to do with the incorrect data type being passed as a prop. Please fix those as well before merging this branch to main.

**Comment by matthewdbroom13** [comment]
I have adjusted the code to remove the console errors described above and have added default props to LocationPage and SingleReviewTravelo.

**Comment by mik3ycodez** [comment]
If this is being combined in PR #182  - please close pull request if no longer needed.

**Comment by matthewdbroom13** [comment]
No longer necessary - this branch's changes and another branch's changes have been combined into a third branch that a  different PR has been made for instead.

**Pull request closed without merging**
