### PR TITLE
Back-end refactoring

### PR DESCRIPTION
**Pull request by mik3ycodez**

### CODE REVIEW

**Comment by aedanmc** [comment]
I'm seeing a test failure in the CI build. Should I wait to review until after it's fixed?

**Comment by mik3ycodez** [comment]
Yeah, it looks like something we implemented didn't quite make it into the commits. I've updated the endpoint. Waiting for build now...

**Comment by mik3ycodez** [comment]
Build successful. Ready for review.

**Review by aedanmc — APPROVED** [review]
Looks good to me!

**Review by matthewdbroom13 — APPROVED** [review]
LGTM!

**Review by C-Christensen — APPROVED** [review]
LGTM

**Review by mzuniga-1833381 — APPROVED** [review]
lgtm

**Pull request merged**
