### PR TITLE
optimized package.json scripts, restructured cloudbuild.yaml to fix i…

### PR DESCRIPTION
**Pull request by mik3ycodez**
…ssue with npm install

Since we diverged the package.json files to front and back ends, we needed to update the cloudbuild and scripts to accommodate proper install instructions.

### CODE REVIEW

**Review by aedanmc — APPROVED** [review]
Looks good to me!

**Review by aedanmc — CHANGES_REQUESTED** [review]
Something about the way these commands are set up is causing the build to run in a loop. Probably need to check `package.json` and remove that dependency cycle.

**Comment by C-Christensen** [comment]
Need work!

**Review by C-Christensen — CHANGES_REQUESTED** [review]
Missing yaml file

**Comment by C-Christensen** [comment]
Yay!!!!

**Review by C-Christensen — APPROVED** [review]
It looks great. Thanks, Mike!

**Review by C-Christensen — APPROVED** [review]

**Review by aedanmc — APPROVED** [review]
Looks good!

**Pull request merged**
