### PR TITLE
fixed ## User Guide FAQ and Walkthrough link - missing aedanmc in url

### PR DESCRIPTION
**Pull request by mik3ycodez**
User Guide heading URL missing 'aedanmc' and causing not found

### CODE REVIEW

**Review by C-Christensen — APPROVED** [review]
LGTM

**Review by C-Christensen — CHANGES_REQUESTED** [review]
We have a link to the Bug Tracking doc twice. Can you please remove one of them so we can merge all of the changes together? Thank you

**Comment by mik3ycodez** [comment]
Also updating Back-end Testing link 404 error

**Review by C-Christensen — APPROVED** [review]
That's perfect. Thank you, Mike!

**Pull request merged**
