### PR TITLE
 Updated database dev documentation with instructions for the local db

### PR DESCRIPTION
**Pull request by C-Christensen**
#89

### CODE REVIEW

**Review by mik3ycodez — CHANGES_REQUESTED** [review]
Spelling errors: 
- Line 12: *utiliing* -> utilizing
- Line 34: *datable* -> table

**Comment by C-Christensen** [comment]
Thank you. I'll get it fixed by EOD.

**Comment by mik3ycodez** [comment]
LGTM

**Review by mik3ycodez — APPROVED** [review]
LGTM

**Pull request merged**
